### ISSUE TITLE
Not smart, imo

### ISSUE THREAD

**Issue by J0NY97** [Epicurius/C-Libraries#1]
https://github.com/Epicurius/C-Libraries/blob/f70c2aa9053d0cb0a7bf67de13ce6361bcee3074/libft/srcs/ft_strsplit.c#L64

maybe you should keep the libc functions the same prototype.
if you want to make changes, make new functions.

**Comment by Epicurius** [comment]
What libc function? there is none called ft_strsplit, or strsplit for that matter. Also you don't have to copy code ideas 1:1 you can innovate and improve code to be more useful and faster.
